backbone: ViT-B/32
batch_size: 128
clip_LN_lr: 1.0e-06
clip_lr: 0.0001
clip_trainer: HiCroPL
cross_layer: 2
ctx_init: a photo of a
ctx_init_sketch: a sketch of a
data_dir: ../data/Sketchy
data_split: -1.0
dataset: sketchy_ext
disable_augmentation: false
disable_cross_exchange: false
enhance_text: true
epochs: 8
eval_mode: category
exp_name: Full_TH2_Mode_B
gpt_text_file: gpt_file/sketchy_ext.json
lambda_ce: 0.1
lambda_consistency: 1.0
lambda_cross_modal: 1.0
lambda_text_consistency: 3.0
lambda_visual_cross: 0.5
language_ctx: -1
language_depth: 1
linear_lr: 0.0001
max_size: 224
n_ctx: 2
n_prompts: 3
nclass: 10
num_trainable_ln: -1
prompt_depth: 3
prompt_dim: 768
prompt_lr: 0.0001
temperature: 0.07
test_batch_size: 1024
th2_mode: B
vision_ctx: -1
vision_depth: -1
workers: 4
